services:
  - type: web
    name: searchable-pdf
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    packages:
      - tesseract-ocr
      - libreoffice
      - libgl1
